image: node:14

stages:
  - setup
  - test

install:
  stage: setup
  script:
    - npm install
  artifacts:
    untracked: true
    expire_in: 60 mins
    paths:
      - .npm/
      - node_modules/

unit-test:
  stage: test
  script:
    - npm run test
  dependencies:
    - install
