image: node:14

stages:
  - setup
  - test

install:
  stage: setup
  script:
    - npm install
  artifacts:
    expire_in: 60 mins
    paths:
      - .npm/
      - node_modules/
      - hello-world/

unit-test:
  stage: test
  script:
    - ls
    - node hello-world/hello-world.js
    - npm run test
  dependencies:
    - install
